[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read-write", path = "script" },
  { access = "read-write", path = "out" },
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]


# Default behaviour changed on commit https://github.com/foundry-rs/foundry/commit/39f13df8971b02f5961d4fd2cb278f44e19a717a
optimizer = true
optimizer_runs = 2000
via_ir = true

no_match_test = "upgrade"

[profile.coverage]
# Exclude script folder from coverage reports (regex pattern)
no_match_coverage = "^script/"

[rpc_endpoints]
mainnet  = "${MAINNET_URL}"
sepolia  = "${SEPOLIA_URL}"
gnosis   = "${GNOSIS_URL}"
arbitrum = "${ARBITRUM_URL}"
base     = "${BASE_URL}"
optimism = "${OP_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }