// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {console} from "forge-std/Script.sol";
import {KpkOivFactory} from "../src/KpkOivFactory.sol";
import {KpkShares} from "../src/kpkShares.sol";
import {OivConfigReader} from "./base/OivConfigReader.sol";

/**
 * Purpose: Deploy a new OIV fund via KpkOivFactory, or the operational stack only for sidechains.
 * Inputs: Path to a JSON config file generated by /deploy-oiv skill. PRIVATE_KEY env var.
 * Outputs: Deployed contract addresses logged to console; broadcast artefacts written by forge.
 * Logic:
 *   - predict(configPath): calls predictOivAddresses without broadcasting, shows expected addresses.
 *   - deployOiv(configPath): calls factory.deployOiv — full fund (shares + infra). Use on mainnet.
 *   - deployStack(configPath): calls factory.deployStack — infra only. Use on sidechains.
 * Assumptions:
 *   - PRIVATE_KEY env var holds the deployer's hex private key (with or without 0x prefix).
 *   - The KpkOivFactory is deployed at FACTORY on every supported chain. NOTE: `FACTORY` is the
 *     factory's CREATE2 address, which is a function of its bytecode — update this constant whenever
 *     the factory is redeployed after a bytecode change (e.g. the `oivToStackConfig` addition lands
 *     the factory at a new address).
 *   - Cross-chain determinism: the same PRIVATE_KEY must broadcast deployStack on every sidechain.
 * Known limitations:
 *   - predict() must be called with --rpc-url pointing to a chain where the factory is deployed.
 *   - additionalAssets is bounded by OivConfigReader.MAX_ADDITIONAL_ASSETS (reverts if exceeded).
 */
contract DeployOiv is OivConfigReader {
    // Update this when the factory is redeployed (its CREATE2 address changes with its bytecode).
    address constant FACTORY = 0x0d94255fdE65D302616b02A2F070CdB21190d420;

    // ── Entry points ───────────────────────────────────────────────────────────

    function predict(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address caller = vm.addr(deployerKey);

        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);
        KpkOivFactory.OivInstance memory predicted = KpkOivFactory(FACTORY).predictOivAddresses(config, caller);

        console.log("============================================================");
        console.log("  Predicted addresses (no deployment)");
        console.log("============================================================");
        _logInstance(predicted);
        console.log("------------------------------------------------------------");
        console.log("  Caller (deployer):    ", caller);
        console.log("  NOTE: these addresses are identical across all chains");
        console.log("        when the same caller and the same salt are used.");
        console.log("============================================================");
    }

    function deployOiv(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.OivInstance memory instance = KpkOivFactory(FACTORY).deployOiv(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  OIV Deployed");
        console.log("============================================================");
        _logInstance(instance);
        console.log("============================================================");
    }

    function deployStack(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        KpkOivFactory.StackConfig memory config = _buildStackConfig(json);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.StackInstance memory instance = KpkOivFactory(FACTORY).deployStack(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  Stack Deployed");
        console.log("============================================================");
        console.log("  Avatar Safe:          ", instance.avatarSafe);
        console.log("  Manager Safe:         ", instance.managerSafe);
        console.log("  execRolesModifier:    ", instance.execRolesModifier);
        console.log("  subRolesModifier:     ", instance.subRolesModifier);
        console.log("  managerRolesModifier: ", instance.managerRolesModifier);
        console.log("============================================================");
    }
}
