// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Script, console} from "forge-std/Script.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {KpkOivFactory} from "../src/KpkOivFactory.sol";
import {KpkShares} from "../src/kpkShares.sol";

/**
 * Purpose: Deploy a new OIV fund via KpkOivFactory, or the operational stack only for sidechains.
 * Inputs: Path to a JSON config file generated by /deploy-oiv skill. PRIVATE_KEY env var.
 * Outputs: Deployed contract addresses logged to console; broadcast artefacts written by forge.
 * Logic:
 *   - predict(configPath): calls predictOivAddresses without broadcasting, shows expected addresses.
 *   - deployOiv(configPath): calls factory.deployOiv — full fund (shares + infra). Use on mainnet.
 *   - deployStack(configPath): calls factory.deployStack — infra only. Use on sidechains.
 * Assumptions:
 *   - PRIVATE_KEY env var holds the deployer's hex private key (with or without 0x prefix).
 *   - The KpkOivFactory is deployed at FACTORY on every supported chain.
 *   - Cross-chain determinism: the same PRIVATE_KEY must broadcast deployStack on every sidechain.
 * Known limitations:
 *   - kpkSharesImpl and kpkSharesProxy addresses cannot be predicted (they use plain CREATE).
 *   - predict() must be called with --rpc-url pointing to a chain where the factory is deployed.
 *   - Additional assets array is capped at 20 entries.
 */
contract DeployFund is Script {
    using stdJson for string;

    address constant FACTORY = 0x0d94255fdE65D302616b02A2F070CdB21190d420;

    // ── Entry points ───────────────────────────────────────────────────────────

    function predict(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address caller = vm.addr(deployerKey);

        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);
        KpkOivFactory.OivInstance memory predicted = KpkOivFactory(FACTORY).predictOivAddresses(config, caller);

        console.log("============================================================");
        console.log("  Direcciones predichas (sin deployment)");
        console.log("============================================================");
        console.log("  Avatar Safe:          ", predicted.avatarSafe);
        console.log("  Manager Safe:         ", predicted.managerSafe);
        console.log("  execRolesModifier:    ", predicted.execRolesModifier);
        console.log("  subRolesModifier:     ", predicted.subRolesModifier);
        console.log("  managerRolesModifier: ", predicted.managerRolesModifier);
        console.log("  kpkShares impl:        (no predecible: usa CREATE, depende de nonce)");
        console.log("  kpkShares proxy:       (no predecible: usa CREATE, depende de nonce)");
        console.log("------------------------------------------------------------");
        console.log("  Caller (deployer):    ", caller);
        console.log("  NOTA: estas direcciones son identicas en todas las chains");
        console.log("        si se usa el mismo caller y el mismo salt.");
        console.log("============================================================");
    }

    function deployOiv(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.OivInstance memory instance = KpkOivFactory(FACTORY).deployOiv(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  OIV Deployed");
        console.log("============================================================");
        console.log("  Avatar Safe:          ", instance.avatarSafe);
        console.log("  Manager Safe:         ", instance.managerSafe);
        console.log("  execRolesModifier:    ", instance.execRolesModifier);
        console.log("  subRolesModifier:     ", instance.subRolesModifier);
        console.log("  managerRolesModifier: ", instance.managerRolesModifier);
        console.log("  kpkShares impl:       ", instance.kpkSharesImpl);
        console.log("  kpkShares proxy:      ", instance.kpkSharesProxy);
        console.log("============================================================");
    }

    function deployStack(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        KpkOivFactory.StackConfig memory config = _buildStackConfig(json);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.StackInstance memory instance = KpkOivFactory(FACTORY).deployStack(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  Stack Deployed");
        console.log("============================================================");
        console.log("  Avatar Safe:          ", instance.avatarSafe);
        console.log("  Manager Safe:         ", instance.managerSafe);
        console.log("  execRolesModifier:    ", instance.execRolesModifier);
        console.log("  subRolesModifier:     ", instance.subRolesModifier);
        console.log("  managerRolesModifier: ", instance.managerRolesModifier);
        console.log("============================================================");
    }

    // ── Config builders ────────────────────────────────────────────────────────

    function _buildOivConfig(string memory json) internal view returns (KpkOivFactory.OivConfig memory config) {
        config.managerSafe.owners = json.readAddressArray(".managerSafe.owners");
        config.managerSafe.threshold = json.readUint(".managerSafe.threshold");
        config.salt = json.readUint(".salt");
        config.admin = json.readAddress(".oiv.admin");

        config.sharesParams.asset = json.readAddress(".oiv.sharesParams.asset");
        config.sharesParams.name = json.readString(".oiv.sharesParams.name");
        config.sharesParams.symbol = json.readString(".oiv.sharesParams.symbol");
        config.sharesParams.subscriptionRequestTtl = uint64(json.readUint(".oiv.sharesParams.subscriptionRequestTtl"));
        config.sharesParams.redemptionRequestTtl = uint64(json.readUint(".oiv.sharesParams.redemptionRequestTtl"));
        config.sharesParams.feeReceiver = json.readAddress(".oiv.sharesParams.feeReceiver");
        config.sharesParams.managementFeeRate = json.readUint(".oiv.sharesParams.managementFeeRate");
        config.sharesParams.redemptionFeeRate = json.readUint(".oiv.sharesParams.redemptionFeeRate");
        config.sharesParams.performanceFeeModule = json.readAddress(".oiv.sharesParams.performanceFeeModule");
        config.sharesParams.performanceFeeRate = json.readUint(".oiv.sharesParams.performanceFeeRate");

        config.additionalAssets = _readAdditionalAssets(json);
    }

    function _buildStackConfig(string memory json) internal view returns (KpkOivFactory.StackConfig memory config) {
        config.managerSafe.owners = json.readAddressArray(".managerSafe.owners");
        config.managerSafe.threshold = json.readUint(".managerSafe.threshold");
        config.execRolesMod.finalOwner = json.readAddress(".execRolesModFinalOwner");
        config.salt = json.readUint(".salt");
    }

    function _readAdditionalAssets(string memory json)
        internal
        view
        returns (KpkOivFactory.AssetConfig[] memory assets)
    {
        uint256 count = 0;
        for (uint256 i = 0; i < 20; i++) {
            if (!vm.keyExists(json, string.concat(".oiv.additionalAssets[", vm.toString(i), "].asset"))) break;
            count++;
        }

        assets = new KpkOivFactory.AssetConfig[](count);
        for (uint256 i = 0; i < count; i++) {
            string memory base = string.concat(".oiv.additionalAssets[", vm.toString(i), "]");
            assets[i].asset = json.readAddress(string.concat(base, ".asset"));
            assets[i].canDeposit = json.readBool(string.concat(base, ".canDeposit"));
            assets[i].canRedeem = json.readBool(string.concat(base, ".canRedeem"));
        }
    }
}
