// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {console} from "forge-std/Script.sol";
import {KpkOivFactory} from "../src/KpkOivFactory.sol";
import {KpkShares} from "../src/kpkShares.sol";
import {OivConfigReader} from "./base/OivConfigReader.sol";

/**
 * Purpose: Deploy a new OIV fund via KpkOivFactory, or the operational stack only for sidechains.
 * Inputs: Path to a JSON config file generated by /deploy-oiv skill. PRIVATE_KEY env var.
 * Outputs: Deployed contract addresses logged to console; broadcast artefacts written by forge.
 * Logic:
 *   - predict(configPath): calls predictOivAddresses without broadcasting, shows expected addresses.
 *   - deploy(configPath): deploys whichever the chain is configured for, per `.sharesChains`. This is
 *     the entry point for a multichain rollout — the same command on every chain.
 *   - deployOiv(configPath): full fund (shares + infra). Refuses on a chain excluded by .sharesChains.
 *   - deployStack(configPath): infra only.
 * Assumptions:
 *   - PRIVATE_KEY env var holds the deployer's hex private key (with or without 0x prefix).
 *   - The KpkOivFactory is deployed at FACTORY on every supported chain. NOTE: `FACTORY` is the
 *     factory's CREATE2 address, which is a function of its bytecode — update this constant whenever
 *     the factory is redeployed after a bytecode change (e.g. the `oivToStackConfig` addition lands
 *     the factory at a new address).
 *   - Cross-chain determinism: the same PRIVATE_KEY must broadcast deployStack on every sidechain.
 * Known limitations:
 *   - predict() must be called with --rpc-url pointing to a chain where the factory is deployed.
 *   - additionalAssets is bounded by OivConfigReader.MAX_ADDITIONAL_ASSETS (reverts if exceeded).
 */
contract DeployOiv is OivConfigReader {
    /// @dev Salt-v3 KpkOivFactory. Its CREATE2 address is a function of its bytecode, so this must be
    ///      updated whenever the factory changes — `test/FactoryAddressSync.t.sol` asserts it equals
    ///      what `OivChainDeploy` would actually deploy, so a stale value fails CI instead of being
    ///      discovered at deploy time. It was previously left pointing at `0x0d94…d420`, which
    ///      `OivChainDeploy.LEGACY_FACTORY` labels as the pre-v2.1.1 build embedding the vulnerable
    ///      Roles Modifier v2.1.0 — funds deployed through it would have carried that bug.
    address public constant FACTORY = 0xd4B412272A0db75f4dac2d568Fa60aC4075Cf93d;

    // ── Entry points ───────────────────────────────────────────────────────────

    function predict(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address caller = vm.addr(deployerKey);

        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);
        KpkOivFactory.OivInstance memory predicted = KpkOivFactory(FACTORY).predictOivAddresses(config, caller);

        console.log("============================================================");
        console.log("  Predicted addresses (no deployment)");
        console.log("============================================================");
        _logInstance(predicted, _shouldDeployShares(json));
        console.log("------------------------------------------------------------");
        console.log("  Caller (deployer):    ", caller);
        console.log("  NOTE: these addresses are identical across all chains");
        console.log("        when the same caller and the same salt are used.");
        console.log("============================================================");
    }

    /// @notice Deploys whichever of the two a chain is configured for, per `.sharesChains`.
    /// @dev    The intended entry point for a multichain rollout: run the identical command on every
    ///         chain and the config decides which get the shares token and which get the operational
    ///         stack alone. `deployOiv` and `deployStack` remain available for a deliberate override.
    function deploy(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        // `deploy` exists to pick the branch per chain, so it must be TOLD which chains carry
        // shares. `_shouldDeployShares` answers "true" for a config with no `.sharesChains` — the
        // right default for the explicit entry points below, and the wrong one here: run across 19
        // chains it would put a live shares token on every one of them. The explicit
        // `deployOiv` / `deployStack` paths keep the permissive default.
        require(
            vm.keyExists(json, ".sharesChains"),
            "config: deploy(configPath) requires .sharesChains - use deployOiv or deployStack to choose per chain"
        );
        if (_shouldDeployShares(json)) {
            _deployOiv(json);
        } else {
            console.log("  Chain %s is not in .sharesChains - deploying the stack only.", block.chainid);
            _deployStack(json);
        }
    }

    function deployOiv(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        // A config that names its shares chains is an instruction, not a hint. Deploying shares on a
        // chain left off that list would create a fund nobody intended, at an address that then
        // cannot be reused for the stack-only deployment the config did ask for.
        require(
            _shouldDeployShares(json), "config: this chain is not in .sharesChains - use deployStack, or fix the config"
        );
        _deployOiv(json);
    }

    function deployStack(string calldata configPath) external {
        string memory json = vm.readFile(configPath);
        _deployStack(json);
    }

    // ── Internals ──────────────────────────────────────────────────────────────

    /// @dev `.oiv.sharesParams.asset` holds the MAINNET token by convention, so a chain added to
    ///      `.sharesChains` without a matching `.oiv.assetOverrides` entry silently inherits it.
    ///      Nothing downstream rejects that: `_validateOivConfig` only refuses the zero address, and
    ///      the Avatar Safe's `approve` succeeds against a codeless address — so the fund would go
    ///      live denominated in a token that does not exist on its chain. Checked here rather than in
    ///      `OivConfigReader` because the reader is a pure parser, unit-tested without a fork.
    function _requireAssetIsLive(KpkOivFactory.OivConfig memory config) internal view {
        require(
            config.sharesParams.asset.code.length != 0,
            "config: base asset has no code on this chain - add an .oiv.assetOverrides entry for it"
        );
    }

    function _deployOiv(string memory json) internal {
        KpkOivFactory.OivConfig memory config = _buildOivConfig(json);
        _requireAssetIsLive(config);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.OivInstance memory instance = KpkOivFactory(FACTORY).deployOiv(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  OIV Deployed");
        console.log("============================================================");
        _logInstance(instance, true);
        console.log("============================================================");
    }

    function _deployStack(string memory json) internal {
        KpkOivFactory.StackConfig memory config = _buildStackConfig(json);

        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerKey);
        KpkOivFactory.StackInstance memory instance = KpkOivFactory(FACTORY).deployStack(config);
        vm.stopBroadcast();

        console.log("============================================================");
        console.log("  Stack Deployed");
        console.log("============================================================");
        console.log("  Avatar Safe:          ", instance.avatarSafe);
        console.log("  Manager Safe:         ", instance.managerSafe);
        console.log("  execRolesModifier:    ", instance.execRolesModifier);
        console.log("  subRolesModifier:     ", instance.subRolesModifier);
        console.log("  managerRolesModifier: ", instance.managerRolesModifier);
        console.log("  exec timelock:        ", instance.execTimelock);
        console.log("============================================================");
    }
}
